/* Licensed under Apache-2.0 */

#ifndef PYROSCOPE_FFI_H_
#define PYROSCOPE_FFI_H_

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct {
  uint32_t index;
} FFIInternedString;

typedef struct {
  const char *data;
  uintptr_t len;
} FFIStringView;

typedef struct {
  FFIInternedString function_name;
  FFIInternedString file_name;
  int line;
} FFIFrame;

typedef struct {
  uintptr_t heap_space;
  uintptr_t alloc_space;
  uintptr_t alloc_count;
} FFIHeapSampleValues;

typedef struct {
  const FFIFrame *frames;
  uintptr_t len;
  FFIHeapSampleValues values;
} FFISample;

#endif  /* PYROSCOPE_FFI_H_ */
