/* Licensed under Apache-2.0 */

#ifndef PYROSCOPE_FFI_H_
#define PYROSCOPE_FFI_H_

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct {
  uint32_t index;
} FFIInternedString;

typedef struct {
  FFIInternedString function_name;
  FFIInternedString file_name;
  int line;
} FFIFrame;

typedef struct {
  uintptr_t heap_space;
  uintptr_t heap_count;
  uintptr_t alloc_space;
  uintptr_t alloc_count;
} FFIHeapSampleValues;

typedef struct {
  const FFIFrame *frames;
  uintptr_t len;
  FFIHeapSampleValues values;
} FFISample;

typedef struct {
  const char *data;
  uintptr_t len;
} FFIStringView;

extern void memalloc_heap_postfork_child(void);

void pyroscope_memprof_push_sample(FFISample sample);

/*
 Intern `s` and return its index.

 Infallible, and callers must not try to detect failure: null data, a zero
 length, and a poisoned lock all yield index 0, which is the index of the
 empty string and therefore a perfectly usable id. This is the one place
 this differs from Datadog's `intern_string`, which returns
 `std::optional` because libdatadog's Profiles Dictionary can fail to
 allocate.

 # Safety

 `s.data[..s.len]` must be valid UTF-8 and must stay alive for the duration
 of the call. The UTF-8 check is skipped because this runs on the sampling
 path; the strings come from CPython's interned name and filename objects.
 */
FFIInternedString pyroscope_string_table_intern_string(FFIStringView s);

#endif  /* PYROSCOPE_FFI_H_ */
